version: "3.3"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "8088:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  rl_app:
    build: .
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - redis
